// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_rMyNHW5By3OgldmFFyjrUfgx7fkb9M',
    appId: '1:490514806005:web:650dba2e536d84a7ec01bc',
    messagingSenderId: '490514806005',
    projectId: 'speatall-385b8',
    authDomain: 'speatall-385b8.firebaseapp.com',
    storageBucket: 'speatall-385b8.appspot.com',
    measurementId: 'G-RQK2K8LWF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIoXqThFpfTBkNxniWXMpHcz0cLscSnYA',
    appId: '1:490514806005:android:081d14cd4f9fa0dcec01bc',
    messagingSenderId: '490514806005',
    projectId: 'speatall-385b8',
    storageBucket: 'speatall-385b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzr8gw-in5VCNG0RUYl9yaIO7U9BTSWxE',
    appId: '1:490514806005:ios:e8ada9be2637cf06ec01bc',
    messagingSenderId: '490514806005',
    projectId: 'speatall-385b8',
    storageBucket: 'speatall-385b8.appspot.com',
    iosClientId: '490514806005-dae3he1jm2k7c40cmqmr8ki6m74ks4jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.speatallapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzr8gw-in5VCNG0RUYl9yaIO7U9BTSWxE',
    appId: '1:490514806005:ios:e7eed7fb8004078cec01bc',
    messagingSenderId: '490514806005',
    projectId: 'speatall-385b8',
    storageBucket: 'speatall-385b8.appspot.com',
    iosClientId: '490514806005-q3ofbrupq6jcqjm2r2k2ugerhpfsku7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.speatallapp.RunnerTests',
  );
}
